"""export trained LM + tokenizer to a self-contained C file (ESP32-C3 target)

int8 weights in flash, Q16.16 fixed-point activations in SRAM, zero heap allocation
"""

import json
import os
import numpy as np
import torch
from pathlib import Path


def _quant(t: torch.Tensor):
    arr   = t.detach().float().numpy()
    amax  = float(np.abs(arr).max())
    scale = amax / 127.0 if amax > 0.0 else 1.0
    q     = np.clip(np.round(arr / scale), -127, 127).astype(np.int8)
    return q, scale


_RODATA = 'RODATA'

def _fmt_i8(name, arr):
    flat  = arr.flatten()
    lines = [f"static const int8_t {_RODATA} {name}[{flat.size}] = {{"]
    for i in range(0, len(flat), 16):
        lines.append("    " + ", ".join(f"{int(v):4d}" for v in flat[i:i+16]) + ",")
    lines.append("};")
    return "\n".join(lines)

def _fmt_q16(name, arr):
    """Float numpy array → Q16.16 int32 C array (value × 65536, rounded)."""
    flat = arr.flatten()
    vals = [int(round(float(v) * 65536)) for v in flat]
    lines = [f"static const int32_t {_RODATA} {name}[{len(vals)}] = {{"]
    for i in range(0, len(vals), 8):
        lines.append("    " + ", ".join(f"{v:9d}" for v in vals[i:i+8]) + ",")
    lines.append("};")
    return "\n".join(lines)

def _to_q16(f: float) -> int:
    return int(round(f * 65536))



def _c_str(data: bytes) -> str:
    # octal not hex: \x81a is parsed as one token (0x81a), \201a is \201 + 'a'
    out = '"'
    for b in data:
        if   b == ord('\\'):  out += '\\\\'
        elif b == ord('"'):   out += '\\"'
        elif 32 <= b <= 126:  out += chr(b)
        else:                 out += f'\\{b:03o}'
    return out + '"'


def _load_tokenizer(tok_path: str):
    with open(tok_path) as f:
        data = json.load(f)

    vocab     = data["model"]["vocab"]
    id_to_str = {v: k for k, v in vocab.items()}
    n_vocab   = len(vocab)

    N_SPECIAL = 7  # [UNK][PAD][BOS][EOS][SEP][A][B]

    id_to_bytes = {}
    for tid in range(n_vocab):
        tok_str = id_to_str.get(tid, "")
        id_to_bytes[tid] = b"" if tid < N_SPECIAL else tok_str.encode("utf-8")

    # longest-first so C greedy MaxMatch finds best match in one pass
    mm_entries = []
    for tok_str, tid in vocab.items():
        if tid < N_SPECIAL:
            continue
        bstr = tok_str.encode("utf-8")
        mm_entries.append((len(bstr), bstr, tid))
    mm_entries.sort(key=lambda x: x[0], reverse=True)
    mm_ids  = [e[2] for e in mm_entries]
    mm_lens = [e[0] for e in mm_entries]

    return id_to_bytes, mm_ids, mm_lens, n_vocab



_TOKENIZER_JSON = os.path.join(os.path.dirname(__file__), '..', 'tokenizer', 'tokenizer.json')

def export(model, out_path: str = "model.c",
           tok_path: str = _TOKENIZER_JSON) -> None:

    dim      = model.emb.embedding_dim
    vocab    = model.emb.num_embeddings
    mem_dim  = model.mem_dim
    n_layers = model.n_layers
    up_dim   = model.layers[0].up_proj.out_features
    cat_dim  = dim + mem_dim

    q_emb, s_emb = _quant(model.emb.weight)
    q_tok, s_tok = _quant(model.token_proj.weight)
    q_mgw, s_mgw = _quant(model.mem_gate.weight)
    f_mgb        = model.mem_gate.bias.detach().float().numpy()
    f_mng        = model.mem_norm.gamma.detach().float().numpy()
    f_ong        = model.out_norm.gamma.detach().float().numpy()
    f_decay      = torch.sigmoid(model.mem_decay).detach().float().numpy()

    layers = []
    for lay in model.layers:
        layers.append({
            "up_w":   _quant(lay.up_proj.weight),
            "gate_w": _quant(lay.gate_proj.weight),
            "mem_w":  _quant(lay.mem_proj.weight),
            "down_w": _quant(lay.down_proj.weight),
            "norm_g": lay.norm.gamma.detach().float().numpy(),
        })

    # SiLU LUT: 256 Q16.16 entries, x ∈ [-8, 8) step 0.0625
    import math
    silu_lut = [_to_q16(((i - 128) / 16.0) / (1.0 + math.exp(-(i - 128) / 16.0)))
                for i in range(256)]

    id_to_bytes, mm_ids, mm_lens, tok_vocab_size = _load_tokenizer(tok_path)
    assert tok_vocab_size == vocab, \
        f"Tokenizer vocab {tok_vocab_size} != model vocab {vocab}"
    n_maxmatch = len(mm_ids)

    sec = []
    def ln(s=""): sec.append(s)
    def hdr(t):   ln(f"/* -- {t} {'-' * max(0, 63 - len(t))} */")

    ln("/*")
    ln(f" * model.c  -  auto-generated LM + tokenizer for ESP32-C3")
    ln(f" * dim={dim}  mem_dim={mem_dim}  up_dim={up_dim}"
       f"  vocab={vocab}  layers={n_layers}  maxmatch={n_maxmatch}")
    ln( " *")
    ln( " * Weights: int8 in flash. Activations + state: Q16.16 fixed-point in SRAM.")
    ln( " * Zero heap allocation. Zero stack allocation in hot path.")
    ln( " * No float in hot path - int32 MAC + integer rmsnorm + SiLU LUT.")
    ln( " * Compile flags: -lm  (rand only; math.h used for sampling exp)")
    ln(" */")
    ln()
    ln("#include <stdint.h>")
    ln("#include <stdlib.h>")
    ln("#include <string.h>")
    ln("#include <math.h>")
    ln()
    ln("/* -- Platform detection ----------------------------------------------------- */")
    ln("/* ESP_PLATFORM is set by ESP-IDF cmake.  __riscv catches bare-metal RISC-V.  */")
    ln("#if defined(ESP_PLATFORM) || defined(__riscv)")
    ln("/* -- ESP32 target --------------------------------------------------------- */")
    ln("/* Weights are int8 in flash (~3 MB). Activations are float32 in SRAM.       */")
    ln("/* Model fits: 3 MB weights + ~30 KB SRAM buffers + 2 KB LMState.           */")
    ln("#  define RODATA __attribute__((aligned(4), section(\".rodata\")))  /* → flash */")
    ln("#  ifndef restrict")
    ln("#    define restrict __restrict__")
    ln("#  endif")
    ln("#elif defined(__GNUC__) || defined(__clang__)")
    ln("/* -- PC / Linux / macOS --------------------------------------------------- */")
    ln("#  define RODATA __attribute__((aligned(4)))")
    ln("#  ifndef restrict")
    ln("#    define restrict __restrict__")
    ln("#  endif")
    ln("#elif defined(_MSC_VER)")
    ln("/* -- Windows (MSVC) ------------------------------------------------------- */")
    ln("#  define RODATA __declspec(align(4))")
    ln("#  define restrict __restrict")
    ln("#else")
    ln("#  define RODATA")
    ln("#endif")
    ln()

    hdr("Types")
    ln()
    ln(f"#define DIM       {dim}")
    ln(f"#define MEM_DIM   {mem_dim}")
    ln(f"#define UP_DIM    {up_dim}")
    ln(f"#define VOCAB     {vocab}")
    ln(f"#define CAT_DIM   {cat_dim}")
    ln(f"#define N_MAXMATCH {n_maxmatch}")
    ln(f"#define MAX_TOKENS  128          /* max encode/decode sequence length */")
    ln(f"#define MAX_GEN     64           /* max tokens to generate per turn   */")
    ln(f"#define MAX_VEC_DIM (2*MEM_DIM)  /* largest matvec col dimension       */")
    ln(f"#define SAMPLE_TOP_K 8           /* top-k candidates for sampling      */")
    ln()
    ln(f"#define BOS_ID    2")
    ln(f"#define EOS_ID    3")
    ln(f"#define SEP_ID    4")
    ln(f"#define SPK_A_ID  5")
    ln(f"#define SPK_B_ID  6")
    ln()
    ln("/* Q16.16 fixed-point: int32_t N represents real value N/65536. */")
    ln("typedef int32_t q16_t;")
    ln("#define Q_ONE     ((q16_t)65536)")
    ln("/* Q_MUL: Q16 × Q16 → Q16 via int64 intermediate, no overflow. */")
    ln("#define Q_MUL(a,b) ((q16_t)(((int64_t)(a)*(int64_t)(b))>>16))")
    ln()
    ln("/* Persistent model memory - zero-init once, carry across calls. */")
    ln("typedef struct { q16_t mem[MEM_DIM]; } LMState;")
    ln()
    ln("/* Token sequence - used for both encode input and decode output. */")
    ln("typedef struct { int16_t ids[MAX_TOKENS]; int len; } Tokens;")
    ln()

    hdr("Quantisation scales - Q16.16 (value = define / 65536)")
    ln(f"#define S_EMB  {_to_q16(s_emb)}")
    ln(f"#define S_TOK  {_to_q16(s_tok)}")
    ln(f"#define S_MGW  {_to_q16(s_mgw)}")
    for i, ld in enumerate(layers):
        _, s_up   = ld["up_w"]
        _, s_gate = ld["gate_w"]
        _, s_mem  = ld["mem_w"]
        _, s_down = ld["down_w"]
        ln(f"#define S_L{i}_UP    {_to_q16(s_up)}")
        ln(f"#define S_L{i}_GATE  {_to_q16(s_gate)}")
        ln(f"#define S_L{i}_MEM   {_to_q16(s_mem)}")
        ln(f"#define S_L{i}_DOWN  {_to_q16(s_down)}")
    ln()

    hdr("Model weights (.rodata / flash)")
    ln()
    ln(_fmt_i8("emb_w",  q_emb));  ln()
    ln(_fmt_i8("tok_w",  q_tok));  ln()
    ln(_fmt_i8("mg_w",   q_mgw));  ln()
    ln(_fmt_q16("mg_b",  f_mgb));  ln()
    ln(_fmt_q16("mn_g",  f_mng));  ln()
    ln(_fmt_q16("on_g",  f_ong));  ln()
    ln(_fmt_q16("decay", f_decay)); ln()
    ln("static const int32_t " + _RODATA + " silu_lut[256] = {")
    for i in range(0, 256, 8):
        ln("    " + ", ".join(f"{silu_lut[j]:9d}" for j in range(i, min(i+8, 256))) + ",")
    ln("};")
    ln()
    for i, ld in enumerate(layers):
        ln(f"/* layer {i} */")
        ln(_fmt_i8(f"l{i}_up_w",   ld["up_w"][0]));   ln()
        ln(_fmt_i8(f"l{i}_gate_w", ld["gate_w"][0])); ln()
        ln(_fmt_i8(f"l{i}_mem_w",  ld["mem_w"][0]));  ln()
        ln(_fmt_i8(f"l{i}_down_w", ld["down_w"][0])); ln()
        ln(_fmt_q16(f"l{i}_ng",    ld["norm_g"]));    ln()

    hdr("Tokenizer data (.rodata / flash)")
    ln()
    ln(f"static const char * const tok_vocab[VOCAB] = {{")
    for tid in range(vocab):
        s    = _c_str(id_to_bytes.get(tid, b""))
        name = {0:"[UNK]",1:"[PAD]",2:"[BOS]",3:"[EOS]",
                4:"[SEP]",5:"[A]",6:"[B]"}.get(tid, "")
        comment = f"  /* {tid:4d} {name} */" if name else f"  /* {tid:4d} */"
        sep = "," if tid < vocab - 1 else ""
        ln(f"    {s}{sep}{comment}")
    ln("};")
    ln()

    ln("static const int16_t tok_mm_ids[N_MAXMATCH] = {")
    for i in range(0, n_maxmatch, 16):
        ln("    " + ", ".join(f"{mm_ids[j]:5d}" for j in range(i, min(i+16, n_maxmatch))) + ",")
    ln("};")
    ln()

    ln("static const uint8_t tok_mm_lens[N_MAXMATCH] = {")
    for i in range(0, n_maxmatch, 16):
        ln("    " + ", ".join(f"{mm_lens[j]:3d}" for j in range(i, min(i+16, n_maxmatch))) + ",")
    ln("};")
    ln()

    hdr("SRAM work buffers (static - zero heap/stack in hot path)")
    ln("static q16_t   wb_h[DIM];")
    ln("static q16_t   wb_nmem[MEM_DIM];")
    ln("static q16_t   wb_up[UP_DIM];")
    ln("static q16_t   wb_gate[UP_DIM];")
    ln("static q16_t   wb_latent[UP_DIM];")
    ln("static q16_t   wb_cat[MAX_VEC_DIM]; /* max(CAT_DIM, 2*MEM_DIM) */")
    ln("static q16_t   wb_tmp[MEM_DIM];")
    ln("static q16_t   wb_px[DIM];")
    ln("static q16_t   wb_logits[VOCAB];")
    ln("static int8_t  wb_xq[MAX_VEC_DIM];  /* int8 activation scratch for MAC         */")
    ln("static float   wb_tv[SAMPLE_TOP_K]; /* top-k sampling: logit values (float OK) */")
    ln("static int16_t wb_ti[SAMPLE_TOP_K]; /* top-k sampling: token indices           */")
    ln()

    hdr("Math helpers - Q16.16 fixed-point, no float in hot path")
    ln()
    ln("/*")
    ln(" * Integer square root (Newton-Raphson). Returns floor(sqrt(n)).")
    ln(" * Converges in ~5 iterations for 64-bit input.")
    ln(" */")
    ln("static uint32_t isqrt64(uint64_t n) {")
    ln("    if (n == 0) return 0;")
    ln("    uint64_t x = n >> 1;")
    ln("    if (x == 0) return 1;")
    ln("    uint64_t y;")
    ln("    do { y = x; x = (y + n / y) >> 1; } while (x < y);")
    ln("    return (uint32_t)y;")
    ln("}")
    ln()
    ln("/*")
    ln(" * RMSNorm in Q16.16.")
    ln(" * sum of squares accumulated as int64 (Q32.32 since x[i] is Q16.16).")
    ln(" * inv_rms = 2^32 / isqrt(ss/dim)  (Q16.16 inverse).")
    ln(" * On RV32IM: all integer ops, no softfloat, ~3x faster than float version.")
    ln(" */")
    ln("static void rmsnorm(q16_t *x, const q16_t *gamma, int dim) {")
    ln("    int64_t ss = 0;")
    ln("    for (int i = 0; i < dim; i++) ss += (int64_t)x[i] * x[i];")
    ln("    ss = (ss + (int64_t)(dim >> 1)) / (int64_t)dim;  /* mean square, Q32 */")
    ln("    ss += 4295;  /* epsilon = 1e-6 in Q32 */")
    ln("    uint32_t rms_q16 = isqrt64((uint64_t)ss);")
    ln("    /* inv_rms: 1/rms in Q16 = 2^32/rms_q16 */")
    ln("    q16_t inv_rms = (q16_t)(0x100000000LL / (int64_t)rms_q16);")
    ln("    for (int i = 0; i < dim; i++)")
    ln("        x[i] = Q_MUL(Q_MUL(x[i], inv_rms), gamma[i]);")
    ln("}")
    ln()
    ln("/*")
    ln(" * SiLU via 256-entry Q16.16 LUT, x ∈ [-8, 8).")
    ln(" * idx = (x_q16 + 524288) >> 12.  Outside range: clamp to 0 or x.")
    ln(" * No exp(), no division - pure integer table lookup.")
    ln(" */")
    ln("static inline q16_t q16_silu(q16_t x) {")
    ln("    if (x <= (q16_t)(-8 * 65536)) return 0;")
    ln("    if (x >= (q16_t)( 8 * 65536)) return x;")
    ln("    return silu_lut[(x + 524288) >> 12];")
    ln("}")
    ln()
    ln("/*")
    ln(" * Quantise Q16.16 vector x[cols] → int8 wb_xq[], returns Q16.16 dequant scale.")
    ln(" * One integer division (amax/127) amortised across all cols multiplications.")
    ln(" * Replaces float _qvec: ~50x faster on no-FPU RISC-V (no softfloat divides).")
    ln(" */")
    ln("static q16_t _qvec(const q16_t *restrict x, int cols) {")
    ln("    int32_t amax = 0;")
    ln("    for (int j = 0; j < cols; j++) {")
    ln("        int32_t a = x[j] < 0 ? -x[j] : x[j];")
    ln("        if (a > amax) amax = a;")
    ln("    }")
    ln("    if (amax == 0) { memset(wb_xq, 0, (size_t)cols); return Q_ONE; }")
    ln("    /* inv_scale = 127/amax in Q16, used for quantising */")
    ln("    q16_t inv_sc = (q16_t)((127LL << 16) / amax);")
    ln("    for (int j = 0; j < cols; j++) {")
    ln("        int32_t q = Q_MUL(x[j], inv_sc);")
    ln("        wb_xq[j] = (int8_t)(q > 127 ? 127 : (q < -127 ? -127 : q));")
    ln("    }")
    ln("    /* dequant scale = amax/127 in Q16 */")
    ln("    return (q16_t)(((int64_t)amax << 16) / 127LL);")
    ln("}")
    ln()
    ln("/*")
    ln(" * int8 × int8 → int32 MAC, dequant to Q16.16.")
    ln(" * y[i] = acc × w_scale × x_scale  (all Q16.16, no float).")
    ln(" * w_scale is a Q16.16 compile-time constant (S_Lx_UP etc.).")
    ln(" * Formula: y_q16 = (acc × w_scale_q16 × x_deq_q16) >> 16")
    ln(" *         using 64-bit intermediate to avoid overflow.")
    ln(" */")
    ln("static void matvec(q16_t *restrict y, const int8_t *restrict W,")
    ln("                   q16_t w_scale, const q16_t *restrict x, int rows, int cols) {")
    ln("    q16_t x_deq = _qvec(x, cols);")
    ln("    /* combined = w_scale × x_deq in Q16; acc × combined gives Q16 output */")
    ln("    int64_t combined = ((int64_t)w_scale * (int64_t)x_deq) >> 16;")
    ln("    for (int i = 0; i < rows; i++) {")
    ln("        int32_t acc = 0;")
    ln("        const int8_t *row = W + (int32_t)i * cols;")
    ln("        for (int j = 0; j < cols; j++) acc += (int32_t)row[j] * (int32_t)wb_xq[j];")
    ln("        y[i] = (q16_t)(((int64_t)acc * combined) >> 16);")
    ln("    }")
    ln("}")
    ln()
    ln("static void matvec_b(q16_t *restrict y, const int8_t *restrict W,")
    ln("                     q16_t w_scale, const q16_t *restrict b,")
    ln("                     const q16_t *restrict x, int rows, int cols) {")
    ln("    q16_t x_deq = _qvec(x, cols);")
    ln("    int64_t combined = ((int64_t)w_scale * (int64_t)x_deq) >> 16;")
    ln("    for (int i = 0; i < rows; i++) {")
    ln("        int32_t acc = 0;")
    ln("        const int8_t *row = W + (int32_t)i * cols;")
    ln("        for (int j = 0; j < cols; j++) acc += (int32_t)row[j] * (int32_t)wb_xq[j];")
    ln("        y[i] = (q16_t)(((int64_t)acc * combined) >> 16) + b[i];")
    ln("    }")
    ln("}")
    ln()
    ln("static int _argmax(const q16_t *v, int n) {")
    ln("    int best = 0;")
    ln("    for (int i = 1; i < n; i++) if (v[i] > v[best]) best = i;")
    ln("    return best;")
    ln("}")
    ln()
    ln("/* lm_expf: only used in lm_sample temperature path (≤40 calls per token). */")
    ln("#if defined(ESP_PLATFORM) || defined(__riscv)")
    ln("static inline float lm_expf(float x) {")
    ln("    if (x < -87.3f) return 0.0f;")
    ln("    union { float f; int32_t i; } u;")
    ln("    u.i = (int32_t)(12102203.0f * x + 1064866805.0f);")
    ln("    return u.f;")
    ln("}")
    ln("#else")
    ln("static inline float lm_expf(float x) { return expf(x); }")
    ln("#endif")
    ln()

    hdr("Tokenizer")
    ln()
    ln("/*")
    ln(" * tok_encode - text → Tokens  (Metaspace MaxMatch)")
    ln(" * Normalises: lowercase, strip apostrophes, collapse whitespace.")
    ln(" * For each whitespace-separated word, prepends ▁ (U+2581, UTF-8 E2 96 81)")
    ln(" * then greedily matches the longest vocab entry at each byte position.")
    ln(" * tok_mm_ids/tok_mm_lens are sorted by byte length descending, so the")
    ln(" * first match in the scan is always the longest - no backtracking needed.")
    ln(" */")
    ln("void tok_encode(const char *text, Tokens *out) {")
    ln("    out->len = 0;")
    ln("    const uint8_t *p = (const uint8_t *)text;")
    ln("    static uint8_t wb[64];  /* ▁ (3B) + normalised word chars */")
    ln("    while (*p && out->len < MAX_TOKENS) {")
    ln("        /* skip whitespace */")
    ln("        while (*p == ' ' || *p == '\\t' || *p == '\\n' || *p == '\\r') p++;")
    ln("        if (!*p) break;")
    ln("        /* build word: ▁ prefix + normalised ASCII chars */")
    ln("        int wlen = 0;")
    ln("        wb[wlen++] = 0xe2; wb[wlen++] = 0x96; wb[wlen++] = 0x81;")
    ln("        while (*p && *p != ' ' && *p != '\\t' && *p != '\\n' && *p != '\\r'")
    ln("               && wlen < (int)sizeof(wb) - 1) {")
    ln("            uint8_t c = *p++;")
    ln("            if (c == '\\'') continue;")
    ln("            if (c >= 'A' && c <= 'Z') c += 32;")
    ln("            wb[wlen++] = c;")
    ln("        }")
    ln("        wb[wlen] = '\\0';")
    ln("        /* greedy MaxMatch: longest vocab entry at each byte position */")
    ln("        int pos = 0;")
    ln("        while (pos < wlen && out->len < MAX_TOKENS) {")
    ln("            int best_len = 0, best_id = 0;")
    ln("            for (int i = 0; i < N_MAXMATCH; i++) {")
    ln("                int vlen = (int)tok_mm_lens[i];")
    ln("                if (vlen <= best_len) break;  /* sorted desc - no longer match */")
    ln("                if (pos + vlen > wlen) continue;")
    ln("                if (memcmp(wb + pos, tok_vocab[tok_mm_ids[i]], (size_t)vlen) == 0) {")
    ln("                    best_len = vlen;")
    ln("                    best_id  = tok_mm_ids[i];")
    ln("                    break;  /* greedy: first (longest) match wins */")
    ln("                }")
    ln("            }")
    ln("            if (best_len == 0) { pos++; continue; }  /* unknown byte: skip */")
    ln("            out->ids[out->len++] = (int16_t)best_id;")
    ln("            pos += best_len;")
    ln("        }")
    ln("    }")
    ln("}")
    ln()
    ln("/*")
    ln(" * tok_decode - Tokens → UTF-8 text")
    ln(" * ▁ prefix (E2 96 81) → space before the token text (suppressed at position 0).")
    ln(" * NSP_ID → suppress the space before the *next* token.")
    ln(" * Other special tokens (BOS/EOS/etc.) emit nothing.")
    ln(" */")
    ln("void tok_decode(const Tokens *t, char *out, int out_size) {")
    ln("    int pos = 0, suppress = 1;  /* suppress=1 strips leading space */")
    ln("    for (int i = 0; i < t->len && pos < out_size - 1; i++) {")
    ln("        int id = t->ids[i];")
    ln("        if (id < 0 || id >= VOCAB) continue;")
    ln("        const char *s = tok_vocab[id];")
    ln("        if (!*s) continue;  /* empty → special token, skip */")
    ln("        /* ▁ is UTF-8 E2 96 81 - word-start marker → emit space */")
    ln("        if ((uint8_t)s[0]==0xe2 && (uint8_t)s[1]==0x96 && (uint8_t)s[2]==0x81) {")
    ln("            if (!suppress && pos < out_size - 1) out[pos++] = ' ';")
    ln("            suppress = 0;")
    ln("            s += 3;")
    ln("        }")
    ln("        while (*s && pos < out_size - 1) out[pos++] = *s++;")
    ln("    }")
    ln("    out[pos] = '\\0';")
    ln("}")
    ln()

    hdr("LM block")
    ln()
    ln("static void lm_block(")
    ln("    q16_t *h, q16_t *nmem,")
    ln("    const int8_t *up_w,   q16_t s_up,")
    ln("    const int8_t *gate_w, q16_t s_gate,")
    ln("    const int8_t *mem_w,  q16_t s_mem,")
    ln("    const int8_t *down_w, q16_t s_down,")
    ln("    const q16_t  *norm_g)")
    ln("{")
    ln("    memcpy(wb_px, h, DIM * sizeof(q16_t));")
    ln("    rmsnorm(h, norm_g, DIM);")
    ln("    matvec(wb_up, up_w, s_up, h, UP_DIM, DIM);")
    ln("    memcpy(wb_cat,       h,    DIM     * sizeof(q16_t));")
    ln("    memcpy(wb_cat + DIM, nmem, MEM_DIM * sizeof(q16_t));")
    ln("    matvec(wb_gate, gate_w, s_gate, wb_cat, UP_DIM, CAT_DIM);")
    ln("    for (int i = 0; i < UP_DIM; i++)")
    ln("        wb_latent[i] = Q_MUL(q16_silu(wb_gate[i]), wb_up[i]);")
    ln("    matvec(h, down_w, s_down, wb_latent, DIM, UP_DIM);")
    ln("    for (int i = 0; i < DIM; i++) h[i] += wb_px[i];")
    ln("    matvec(wb_tmp, mem_w, s_mem, wb_latent, MEM_DIM, UP_DIM);")
    ln("    for (int i = 0; i < MEM_DIM; i++) nmem[i] += wb_tmp[i];")
    ln("}")
    ln()

    hdr("Core model forward (low-level)")
    ln()
    ln("/* Feed one token through the model. Updates mem in-place, writes Q16.16 logits. */")
    ln("void model_forward(int token_id, q16_t *mem, q16_t *logits) {")
    ln("    /* Embedding: int8 row × Q16.16 scale → Q16.16 (int8 treated as Q0) */")
    ln("    const int8_t *erow = emb_w + (int32_t)token_id * DIM;")
    ln("    for (int i = 0; i < DIM; i++) wb_h[i] = (q16_t)((int32_t)erow[i] * S_EMB);")
    ln("    memcpy(wb_cat,       wb_h, DIM     * sizeof(q16_t));")
    ln("    memcpy(wb_cat + DIM, mem,  MEM_DIM * sizeof(q16_t));")
    ln("    matvec(wb_h, tok_w, S_TOK, wb_cat, DIM, CAT_DIM);")
    ln("    memcpy(wb_nmem, mem, MEM_DIM * sizeof(q16_t));")
    for i, ld in enumerate(layers):
        ln(f"    lm_block(wb_h, wb_nmem,")
        ln(f"             l{i}_up_w, S_L{i}_UP, l{i}_gate_w, S_L{i}_GATE,")
        ln(f"             l{i}_mem_w, S_L{i}_MEM, l{i}_down_w, S_L{i}_DOWN, l{i}_ng);")
    ln("    rmsnorm(wb_nmem, mn_g, MEM_DIM);")
    ln("    memcpy(wb_cat,           mem,     MEM_DIM * sizeof(q16_t));")
    ln("    memcpy(wb_cat + MEM_DIM, wb_nmem, MEM_DIM * sizeof(q16_t));")
    ln("    matvec_b(wb_tmp, mg_w, S_MGW, mg_b, wb_cat, MEM_DIM, 2 * MEM_DIM);")
    ln("    for (int i = 0; i < MEM_DIM; i++) {")
    ln("        q16_t d = decay[i];")
    ln("        mem[i] = Q_MUL(d, mem[i]) + Q_MUL(Q_ONE - d, Q_MUL(q16_silu(wb_tmp[i]), wb_nmem[i]));")
    ln("    }")
    ln("    rmsnorm(wb_h, on_g, DIM);")
    ln("    matvec(logits, emb_w, S_EMB, wb_h, VOCAB, DIM);")
    ln("}")
    ln()

    hdr("High-level API")
    ln()

    ln("/* Zero-initialise model state. Call once before first use. */")
    ln("void lm_init(LMState *s) {")
    ln("    memset(s->mem, 0, sizeof(s->mem));")
    ln("}")
    ln()
    ln("/* Thin wrapper - one token forward, struct-based. */")
    ln("void lm_forward(int token_id, LMState *s, q16_t *logits) {")
    ln("    model_forward(token_id, s->mem, logits);")
    ln("}")
    ln()
    ln("/*")
    ln(" * lm_sample - sample from top-K Q16.16 logits with temperature.")
    ln(" * temp <= 0 → greedy argmax (pure integer, zero float).")
    ln(" * temp >  0 → convert top-K to float for softmax (only 40 softfloat ops).")
    ln(" */")
    ln("int lm_sample(const q16_t *logits, float temp) {")
    ln("    if (temp <= 0.0f) return _argmax(logits, VOCAB);")
    ln("    /* Partial insertion sort: keep top-K sorted descending (integer compare). */")
    ln("    for (int k = 0; k < SAMPLE_TOP_K; k++) { wb_tv[k] = -3.4e38f; wb_ti[k] = 0; }")
    ln("    for (int i = 0; i < VOCAB; i++) {")
    ln("        float lf = (float)logits[i] * (1.0f / 65536.0f);  /* Q16.16 → float */")
    ln("        if (lf <= wb_tv[SAMPLE_TOP_K - 1]) continue;")
    ln("        wb_tv[SAMPLE_TOP_K - 1] = lf;")
    ln("        wb_ti[SAMPLE_TOP_K - 1] = (int16_t)i;")
    ln("        for (int k = SAMPLE_TOP_K - 1; k > 0 && wb_tv[k] > wb_tv[k-1]; k--) {")
    ln("            float   tf = wb_tv[k]; wb_tv[k] = wb_tv[k-1]; wb_tv[k-1] = tf;")
    ln("            int16_t tt = wb_ti[k]; wb_ti[k] = wb_ti[k-1]; wb_ti[k-1] = tt;")
    ln("        }")
    ln("    }")
    ln("    /* Softmax over top-K only - 40 lm_expf calls, not VOCAB. */")
    ln("    float mx = wb_tv[0], sum = 0.0f;")
    ln("    for (int k = 0; k < SAMPLE_TOP_K; k++) {")
    ln("        wb_tv[k] = lm_expf((wb_tv[k] - mx) / temp);")
    ln("        sum += wb_tv[k];")
    ln("    }")
    ln("    float r = ((float)rand() / (float)RAND_MAX) * sum, acc = 0.0f;")
    ln("    for (int k = 0; k < SAMPLE_TOP_K; k++) {")
    ln("        acc += wb_tv[k];")
    ln("        if (acc >= r) return wb_ti[k];")
    ln("    }")
    ln("    return wb_ti[SAMPLE_TOP_K - 1];")
    ln("}")
    ln()
    ln("/*")
    ln(" * lm_respond - full chat turn: encode input, prime model, generate, decode.")
    ln(" * Prompt: [BOS][A]<input>[SEP][B] → generate until [SEP]/[EOS] or MAX_GEN.")
    ln(" */")
    ln("int lm_respond(const char *input, LMState *s,")
    ln("               char *out, int out_size, float temp) {")
    ln("    Tokens prompt = {0};")
    ln("    prompt.ids[prompt.len++] = BOS_ID;")
    ln("    prompt.ids[prompt.len++] = SPK_A_ID;")
    ln("    Tokens enc = {0};")
    ln("    tok_encode(input, &enc);")
    ln("    for (int i = 0; i < enc.len && prompt.len < MAX_TOKENS - 2; i++)")
    ln("        prompt.ids[prompt.len++] = enc.ids[i];")
    ln("    prompt.ids[prompt.len++] = SEP_ID;")
    ln("    prompt.ids[prompt.len++] = SPK_B_ID;")
    ln("    for (int i = 0; i < prompt.len; i++)")
    ln("        model_forward(prompt.ids[i], s->mem, wb_logits);")
    ln("    Tokens resp = {0};")
    ln("    for (int i = 0; i < MAX_GEN; i++) {")
    ln("        int tok = lm_sample(wb_logits, temp);")
    ln("        if (tok == SEP_ID || tok == EOS_ID) break;")
    ln("        if (resp.len < MAX_TOKENS) resp.ids[resp.len++] = (int16_t)tok;")
    ln("        model_forward(tok, s->mem, wb_logits);")
    ln("    }")
    ln("    tok_decode(&resp, out, out_size);")
    ln("    return resp.len;")
    ln("}")
    ln()
    ln("/*")
    ln(" * tok_decode_one - decode a single token id to a UTF-8 string.")
    ln(" * prepend_space=1 adds a leading space before word-start (▁) tokens.")
    ln(" * out must be >= 32 bytes. Returns number of bytes written (excl NUL).")
    ln(" */")
    ln("int tok_decode_one(int tok_id, int prepend_space, char *out, int out_size) {")
    ln("    if (tok_id < 0 || tok_id >= VOCAB || out_size <= 0) {")
    ln("        if (out_size > 0) out[0] = '\\0';")
    ln("        return 0;")
    ln("    }")
    ln("    const char *s = tok_vocab[tok_id];")
    ln("    if (!*s) { out[0] = '\\0'; return 0; }")
    ln("    int pos = 0;")
    ln("    if ((uint8_t)s[0]==0xe2 && (uint8_t)s[1]==0x96 && (uint8_t)s[2]==0x81) {")
    ln("        if (prepend_space && pos < out_size - 1) out[pos++] = ' ';")
    ln("        s += 3;")
    ln("    }")
    ln("    while (*s && pos < out_size - 1) out[pos++] = *s++;")
    ln("    out[pos] = '\\0';")
    ln("    return pos;")
    ln("}")
    ln()
    ln("/*")
    ln(" * lm_prime - encode and feed [BOS][A]<input>[SEP][B], leaving wb_logits ready.")
    ln(" * Must be called before lm_next() for streaming generation.")
    ln(" */")
    ln("void lm_prime(const char *input, LMState *s) {")
    ln("    Tokens prompt = {0};")
    ln("    prompt.ids[prompt.len++] = BOS_ID;")
    ln("    prompt.ids[prompt.len++] = SPK_A_ID;")
    ln("    Tokens enc = {0};")
    ln("    tok_encode(input, &enc);")
    ln("    for (int i = 0; i < enc.len && prompt.len < MAX_TOKENS - 2; i++)")
    ln("        prompt.ids[prompt.len++] = enc.ids[i];")
    ln("    prompt.ids[prompt.len++] = SEP_ID;")
    ln("    prompt.ids[prompt.len++] = SPK_B_ID;")
    ln("    for (int i = 0; i < prompt.len; i++)")
    ln("        model_forward(prompt.ids[i], s->mem, wb_logits);")
    ln("}")
    ln()
    ln("/*")
    ln(" * lm_next - sample one token and advance the model.")
    ln(" * Returns the token id. Returns SEP_ID or EOS_ID at end of turn.")
    ln(" * Call lm_prime() once, then loop lm_next() until a stop token.")
    ln(" */")
    ln("int lm_next(LMState *s, float temp) {")
    ln("    int tok = lm_sample(wb_logits, temp);")
    ln("    if (tok != SEP_ID && tok != EOS_ID)")
    ln("        model_forward(tok, s->mem, wb_logits);")
    ln("    return tok;")
    ln("}")
    ln()
    ln("/*")
    ln(" * lm_next_force - like lm_next but masks SEP/EOS to -inf before sampling.")
    ln(" * Use for the first token of a turn to prevent an empty response.")
    ln(" */")
    ln("int lm_next_force(LMState *s, float temp) {")
    ln("    wb_logits[SEP_ID] = (q16_t)0x80000001;  /* minimum Q16.16 ≈ -inf */")
    ln("    wb_logits[EOS_ID] = (q16_t)0x80000001;")
    ln("    int tok = lm_sample(wb_logits, temp);")
    ln("    model_forward(tok, s->mem, wb_logits);  /* tok is never a stop token */")
    ln("    return tok;")
    ln("}")

    Path(out_path).write_text("\n".join(sec), encoding="utf-8")

    i8_bytes  = (q_emb.size + q_tok.size + q_mgw.size +
                 sum(ld["up_w"][0].size + ld["gate_w"][0].size +
                     ld["mem_w"][0].size + ld["down_w"][0].size for ld in layers))
    q16_bytes = (f_mgb.size + f_mng.size + f_ong.size + f_decay.size +
                 sum(ld["norm_g"].size for ld in layers) + 256) * 4  # +256 silu LUT
    tok_bytes = (sum(len(id_to_bytes.get(i, b"")) for i in range(vocab)) +
                 n_maxmatch * 3)
    sram_bytes = (dim + mem_dim + up_dim * 3 + cat_dim + mem_dim * 2 + dim + vocab) * 4
    sram_bytes += (40 + 20) * 4  # wb_tv, wb_ti (sampling)

    print(f"Exported → {out_path}")
    print(f"  model flash:  {i8_bytes:>7,} B int8  +  {q16_bytes:>5,} B q16"
          f"  =  {(i8_bytes + q16_bytes) / 1024:.1f} KB")
    print(f"  tok flash:   ~{tok_bytes:>6,} B  ({n_maxmatch} maxmatch entries, {vocab} vocab)")
    print(f"  SRAM:        ~{sram_bytes:>6,} B  (+ {mem_dim*4} B LMState caller-owned)")
    print(f"  params: {sum(p.numel() for p in model.parameters()):,}")
